---
- hosts: all
  sudo: true
  vars:
    web_server: apachephp
    servername: dev.010php 192.168.33.100
    timezone: Europe/Amsterdam
  vars_files:
    - vars/common.yml
    - [ "vars/apachephp.yml", "vars/ws_defaults.yml" ]
  roles:
    - init
    - php5-cli
    - apache
    - php5
    - composer
    - phpcommon
    - app
